[workspace]
members = [
    "cargo-ginit",
    "ginit",
]
# We generate a test project on CI in this subdir, so this prevents the test
# project from "believing" it's in the workspace.
exclude = ["tmp"]
