[package]
name = "cargo-ginit"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"

[[bin]]
name = "cargo-ginit"

[dependencies]
colored = "1"
derive_more = "0.14"
env_logger = "0.6"
handlebars = "1"
Inflector = { version = "0.11", default-features = false }
lazy_static = "1"
log = "0.4"
openssl = "0.10"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.2"
toml = "0.4"
