[package]
name = "cargo-mobile"
version = "0.7.0"
authors = ["Francesca Lovebloom <francesca@brainiumstudios.com>"]
edition = "2018"
description = "Rust on mobile made easy!"
documentation = "https://docs.rs/cargo-mobile"
repository = "https://github.com/BrainiumLLC/cargo-mobile"
readme = "README.md"
keywords = ["cargo", "mobile", "ios", "android"]
categories = ["development-tools::cargo-plugins"]
license = "Apache-2.0/MIT"

[[bin]]
name = "cargo-android"
required-features = ["android"]

[[bin]]
name = "cargo-apple"
required-features = ["apple"]

[features]
android = ["java-properties"]
apple = ["openssl", "serde_json"]
brainium = []
default = ["android", "apple", "brainium"]

[dependencies]
bicycle = { git = "https://github.com/BrainiumLLC/bicycle" }
bossy = "0.1.2"
colored = "1.9.3"
deunicode = "1.1.1"
english-numbers = "0.3.3"
env_logger = "0.7.1"
heck = "0.3.1"
home = "0.5.3"
ignore = "0.4.16"
indexmap = "1.3.2"
java-properties = { version = "1.2.0", optional = true }
log = "0.4.8"
once-cell-regex = "0.1.1"
openssl = { version = "0.10.28", optional = true }
path_abs = "0.5.0"
publicsuffix = { version = "1.5.4", default-features = false }
reserved-names = { git = "https://github.com/BrainiumLLC/reserved-names" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0.50", optional = true }
structopt = "0.3.12"
textwrap = { version = "0.11.0", features = ["term_size"] }
toml = { version = "0.5.6", features = ["preserve_order"] }
yes-or-no = { git = "https://github.com/BrainiumLLC/yes-or-no" }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.20.0"
core-foundation = "0.7.0"
objc = "0.2.7"
objc_id = "0.1.1"

[build-dependencies]
bicycle = { git = "https://github.com/BrainiumLLC/bicycle" }
home = "0.5.3"
