[package]
name = "ginit"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"

[dependencies]
bicycle = { git = "ssh://git@bitbucket.org/brainium/bicycle.git" }
colored = "1"
derive_more = "0.15"
Inflector = { version = "0.11", default-features = false }
lazy_static = "1"
log = "0.4"
openssl = "0.10"
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
