[package]
name = "ginit"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"

[features]
android = ["ginit-android"]
brainium = []
default = ["android", "brainium", "ios"]
ios = []

[dependencies]
ginit-android = { path = "../plugins/ginit-android", optional = true }
ginit-core = { path = "../ginit-core" }
log = "0.4.8"
serde = { version = "1.0.101", features = ["derive"] }
toml = "0.5.3"
