[package]
name = "cargo-ginit"
version = "0.4.0"
authors = ["Brainium Studios LLC"]
edition = "2018"
description = "Game dev productivity tools"

[dependencies]
clap = "2.33.0"
colored = "1.8.0"
env_logger = "0.7.1"
ginit = { path = "../ginit" }
