[package]
name = "cargo-ginit"
version = "0.5.0"
authors = ["Brainium Studios LLC"]
edition = "2018"
description = "Game dev productivity tools"

[dependencies]
clap = "2.33.0"
env_logger = "0.6.2"
ginit = { path = "../ginit" }
